/**
 * Curated option lists for Search & Add (combobox + Other).
 * Brands: widely recognized US adult apparel / footwear names (alphabetical).
 */

export const SEARCH_BRANDS: string[] = [
  'Abercrombie & Fitch',
  'Adidas',
  'American Eagle',
  'Ann Taylor',
  'Anthropologie',
  'Athleta',
  'Banana Republic',
  'Brooks Brothers',
  'Calvin Klein',
  'Carhartt',
  'Champion',
  'Coach',
  'Columbia',
  'Converse',
  'Crocs',
  'Dickies',
  'Express',
  'Everlane',
  'Forever 21',
  'Free People',
  'Gap',
  'H&M',
  'Hollister',
  'J.Crew',
  'Kate Spade',
  "Levi's",
  'Loft',
  'Lululemon',
  'Madewell',
  'Michael Kors',
  'New Balance',
  'Nike',
  'Nordstrom',
  'Old Navy',
  'Patagonia',
  'Ralph Lauren',
  'Reebok',
  'Skechers',
  'The North Face',
  'Timberland',
  'Tommy Hilfiger',
  'Tory Burch',
  'UGG',
  'Under Armour',
  'Uniqlo',
  'Urban Outfitters',
  'Vans',
  'Vineyard Vines',
  'Wrangler',
  'Zara',
].sort((a, b) => a.localeCompare(b));

export const SEARCH_COLORS: string[] = [
  'Beige',
  'Black',
  'Blue',
  'Brown',
  'Burgundy',
  'Camel',
  'Charcoal',
  'Coral',
  'Cream',
  'Gold',
  'Gray',
  'Green',
  'Grey',
  'Ivory',
  'Khaki',
  'Lavender',
  'Mint',
  'Multicolor',
  'Navy',
  'Olive',
  'Orange',
  'Pink',
  'Purple',
  'Red',
  'Silver',
  'Tan',
  'Taupe',
  'Teal',
  'White',
  'Yellow',
];

export const SEARCH_MATERIALS: string[] = [
  'Canvas',
  'Cashmere',
  'Chiffon',
  'Corduroy',
  'Cotton',
  'Denim',
  'Fleece',
  'Jersey',
  'Knit',
  'Leather',
  'Linen',
  'Mesh',
  'Nylon',
  'Polyester',
  'Satin',
  'Silk',
  'Spandex',
  'Suede',
  'Tweed',
  'Velvet',
  'Wool',
];

export type SearchGarmentCategory = 'top' | 'bottom' | 'shoes' | 'accessory';

export const SEARCH_KINDS_BY_CATEGORY: Record<SearchGarmentCategory, string[]> = {
  top: [
    'Blouse',
    'Bodysuit',
    'Button-down shirt',
    'Cardigan',
    'Crop top',
    'Flannel shirt',
    'Henley',
    'Hoodie',
    'Oxford shirt',
    'Polo shirt',
    'Sweater',
    'Sweatshirt',
    'T-shirt',
    'Tank top',
    'Turtleneck',
  ],
  bottom: [
    'Cargo pants',
    'Chinos',
    'Culottes',
    'Dress pants',
    'Jeans',
    'Leggings',
    'Shorts',
    'Skirt',
    'Sweatpants',
    'Trousers',
    'Wide-leg pants',
  ],
  shoes: [
    'Ankle boots',
    'Ballet flats',
    'Chelsea boots',
    'Heels',
    'Knee-high boots',
    'Loafers',
    'Oxfords',
    'Running shoes',
    'Sandals',
    'Slides',
    'Sneakers',
  ],
  accessory: [
    'Backpack',
    'Beanie',
    'Belt',
    'Bracelet',
    'Crossbody bag',
    'Earrings',
    'Hair accessory',
    'Handbag',
    'Hat',
    'Necklace',
    'Scarf',
    'Socks',
    'Sunglasses',
    'Tie',
    'Tote bag',
    'Watch',
  ],
};
